modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "trainutilities"
version = "${version}"
displayName = "Create: TrainUtilities"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.trainutilities]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trainutilities]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,]"
ordering="NONE"
side="BOTH"