modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ProgrammerLP/Create-Trainutilities/issues"
license = "AGPL-3"

[[mods]]
modId = "trainutilities"
version = "${version}"
displayName = "Create: TrainUtilities"
authors = "Me!"
description = '''
Mod that adds custom sliding doors with realistic opening & closing sounds and station blocks, and also building blocks for stations and trains.
'''
logoFile = "mod_icon.png"

[[dependencies.trainutilities]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trainutilities]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,]"
ordering="NONE"
side="BOTH"