modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "trainutilities"
version = "${version}"
displayName = "Create Train Utilities"
authors = "ProgrammerLP"
description = '''
Mod that adds custom sliding doors with realistic opening & closing sounds and station blocks, and also building blocks for stations and trains.
'''
logoFile = "mod_icon.png"

[[dependencies.trainutilities]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "dragonlib"
type = "required"
versionRange = "[1.21.1-2.2.24,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "create"
type = "required"
versionRange = "[6.0.6,]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "trainutilities.mixins.json"
